import 'package:flutter/material.dart';

import '../colors/custom_colors.dart';

class ThemeLightColors extends CustomColors {
  ThemeLightColors()
      : super(
          brightness: Brightness.light,
          primary: const Color(0xff904a41),
          surfaceTint: const Color(0xff904a41),
          onPrimary: const Color(0xffffffff),
          primaryContainer: const Color(0xffffdad5),
          onPrimaryContainer: const Color(0xff3b0905),
          secondary: const Color(0xff775652),
          onSecondary: const Color(0xffffffff),
          secondaryContainer: const Color(0xffffdad5),
          onSecondaryContainer: const Color(0xff2c1512),
          tertiary: const Color(0xff006874),
          onTertiary: const Color(0xffffffff),
          tertiaryContainer: const Color(0xff9eeffd),
          onTertiaryContainer: const Color(0xff001f24),
          error: const Color(0xffba1a1a),
          onError: const Color(0xffffffff),
          errorContainer: const Color(0xffffdad6),
          onErrorContainer: const Color(0xff410002),
          background: const Color(0xfffff8f7),
          onBackground: const Color(0xff231918),
          surface: const Color(0xfffff8f7),
          onSurface: const Color(0xff231918),
          surfaceVariant: const Color(0xfff5ddda),
          onSurfaceVariant: const Color(0xff534341),
          outline: const Color(0xff857370),
          outlineVariant: const Color(0xffd8c2be),
          shadow: const Color(0xff000000),
          scrim: const Color(0xff000000),
          inverseSurface: const Color(0xff392e2c),
          inverseOnSurface: const Color(0xffffedea),
          inversePrimary: const Color(0xffffb4a9),
          primaryFixed: const Color(0xffffdad5),
          onPrimaryFixed: const Color(0xff3b0905),
          primaryFixedDim: const Color(0xffffb4a9),
          onPrimaryFixedVariant: const Color(0xff73342b),
          secondaryFixed: const Color(0xffffdad5),
          onSecondaryFixed: const Color(0xff2c1512),
          secondaryFixedDim: const Color(0xffe7bdb6),
          onSecondaryFixedVariant: const Color(0xff5d3f3b),
          tertiaryFixed: const Color(0xff9eeffd),
          onTertiaryFixed: const Color(0xff001f24),
          tertiaryFixedDim: const Color(0xff82d3e0),
          onTertiaryFixedVariant: const Color(0xff004f58),
          surfaceDim: const Color(0xffe8d6d3),
          surfaceBright: const Color(0xfffff8f7),
          surfaceContainerLowest: const Color(0xffffffff),
          surfaceContainerLow: const Color(0xfffff0ee),
          surfaceContainer: const Color(0xfffceae7),
          surfaceContainerHigh: const Color(0xfff7e4e1),
          surfaceContainerHighest: const Color(0xfff1dedc),
        );
}

class ThemeDarkColors extends CustomColors {
  ThemeDarkColors()
      : super(
          brightness: Brightness.dark,
          primary: const Color(0xffffb4a9),
          surfaceTint: const Color(0xffffb4a9),
          onPrimary: const Color(0xff561e17),
          primaryContainer: const Color(0xff73342b),
          onPrimaryContainer: const Color(0xffffdad5),
          secondary: const Color(0xffe7bdb6),
          onSecondary: const Color(0xff442926),
          secondaryContainer: const Color(0xff5d3f3b),
          onSecondaryContainer: const Color(0xffffdad5),
          tertiary: const Color(0xff82d3e0),
          onTertiary: const Color(0xff00363d),
          tertiaryContainer: const Color(0xff004f58),
          onTertiaryContainer: const Color(0xff9eeffd),
          error: const Color(0xffffb4ab),
          onError: const Color(0xff690005),
          errorContainer: const Color(0xff93000a),
          onErrorContainer: const Color(0xffffdad6),
          background: const Color(0xff1a1110),
          onBackground: const Color(0xfff1dedc),
          surface: const Color(0xff1a1110),
          onSurface: const Color(0xfff1dedc),
          surfaceVariant: const Color(0xff534341),
          onSurfaceVariant: const Color(0xffd8c2be),
          outline: const Color(0xffa08c89),
          outlineVariant: const Color(0xff534341),
          shadow: const Color(0xff000000),
          scrim: const Color(0xff000000),
          inverseSurface: const Color(0xfff1dedc),
          inverseOnSurface: const Color(0xff392e2c),
          inversePrimary: const Color(0xff904a41),
          primaryFixed: const Color(0xffffdad5),
          onPrimaryFixed: const Color(0xff3b0905),
          primaryFixedDim: const Color(0xffffb4a9),
          onPrimaryFixedVariant: const Color(0xff73342b),
          secondaryFixed: const Color(0xffffdad5),
          onSecondaryFixed: const Color(0xff2c1512),
          secondaryFixedDim: const Color(0xffe7bdb6),
          onSecondaryFixedVariant: const Color(0xff5d3f3b),
          tertiaryFixed: const Color(0xff9eeffd),
          onTertiaryFixed: const Color(0xff001f24),
          tertiaryFixedDim: const Color(0xff82d3e0),
          onTertiaryFixedVariant: const Color(0xff004f58),
          surfaceDim: const Color(0xff1a1110),
          surfaceBright: const Color(0xff423735),
          surfaceContainerLowest: const Color(0xff140c0b),
          surfaceContainerLow: const Color(0xff231918),
          surfaceContainer: const Color(0xff271d1c),
          surfaceContainerHigh: const Color(0xff322826),
          surfaceContainerHighest: const Color(0xff3d3231),
        );
}
